import pandas as pd
import numpy as np
import joblib
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import warnings

# Suppress minor warnings for clean output
warnings.filterwarnings("ignore")

# ─── 1. Load & Prepare Data ──────────────────────────────────────────────────
print("[1/5] Loading verified dataset...")
try:
    df = pd.read_csv("/kaggle/working/data/noisy_smart_router_data.csv")
except FileNotFoundError:
    raise FileNotFoundError("Please run the data generator script first!")

# Define Features and Target
FEATURES = ["damage_class", "road_type", "relative_bbox_area", "cluster_count"]
CATEGORICAL_FEATURES = ["damage_class", "road_type"]
NUMERIC_FEATURES = ["relative_bbox_area", "cluster_count"]

X = df[FEATURES]

# Explicitly map target to integers to enforce ordinality
TARGET_MAP = {"LOW": 0, "MEDIUM": 1, "HIGH": 2}
REVERSE_MAP = {0: "LOW", 1: "MEDIUM", 2: "HIGH"}
y = df["priority"].map(TARGET_MAP)

# Stratified Split guarantees class distributions match in train and test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

# ─── 2. Build the Production Pipeline ────────────────────────────────────────
print("[2/5] Constructing preprocessing pipeline...")

# One-Hot Encode categoricals, pass through numericals untouched
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), CATEGORICAL_FEATURES)
    ],
    remainder="passthrough"
)

# Initialize Random Forest with balanced weights and anti-overfitting constraints
rf = RandomForestClassifier(
    n_estimators=150,
    max_depth=8,               # Shallow enough to prevent memorizing noise
    min_samples_split=10,      # Requires solid evidence to split a node
    class_weight="balanced",   # Handles the natural class imbalance
    random_state=42,
    n_jobs=-1
)

# The ultimate artifact: Preprocessor + Model
model_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", rf)
])

# ─── 3. Training & Cross-Validation ──────────────────────────────────────────
print("[3/5] Training and validating model...")

# 5-Fold Cross Validation on training data to ensure stability
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_scores = cross_val_score(model_pipeline, X_train, y_train, cv=skf, scoring="f1_macro")

print(f"      → 5-Fold Macro F1: {cv_scores.mean():.4f} (± {cv_scores.std():.4f})")

# Train final pipeline on all training data
model_pipeline.fit(X_train, y_train)

# ─── 4. Evaluation ───────────────────────────────────────────────────────────
print("\n[4/5] Evaluating on unseen test data...")
y_pred = model_pipeline.predict(X_test)

print("\n--- Classification Report ---")
# Use the explicit reverse map to ensure labels read logically
target_names = [REVERSE_MAP[i] for i in range(3)] 
print(classification_report(y_test, y_pred, target_names=target_names))

print("--- Confusion Matrix ---")
cm = confusion_matrix(y_test, y_pred)
cm_df = pd.DataFrame(cm, index=target_names, columns=target_names)
print(cm_df)

# Feature Importance extraction from pipeline
# (Requires retrieving feature names generated by OneHotEncoder)
ohe = model_pipeline.named_steps["preprocessor"].named_transformers_["cat"]
cat_features_out = ohe.get_feature_names_out(CATEGORICAL_FEATURES)
all_feature_names = list(cat_features_out) + NUMERIC_FEATURES

importances = model_pipeline.named_steps["classifier"].feature_importances_
fi_df = pd.DataFrame({"Feature": all_feature_names, "Importance": importances})
fi_df = fi_df.sort_values(by="Importance", ascending=False)

print("\n--- Top 5 Feature Importances ---")
for _, row in fi_df.head(5).iterrows():
    bar = "█" * int(row['Importance'] * 50)
    print(f"  {row['Feature']:<30} {bar} {row['Importance']:.3f}")

# ─── 5. Export for FastAPI ───────────────────────────────────────────────────
print("\n[5/5] Exporting production artifact...")
joblib.dump(model_pipeline, "priority_router_pipeline.pkl")
joblib.dump(REVERSE_MAP, "target_map.pkl")
print("      → Saved 'priority_router_pipeline.pkl'")
print("      → Done. Ready for inference.")